### ISSUE TITLE
Update RHEL version for AMMOS compatibility

### ISSUE THREAD

**Issue by BrianSipos** [NASA-AMMOS/anms#52]
The AMMOS baseline targeted by ANMSv1.0 is on RHEL 8.6, while future AMMOS baseline will be RHEL 9. This ticket is to track updates needed to use RHEL UBI 9.2 base image.
```[tasklist]
### Tasks
- [x] create a new RHEL 9 cloud VM
- [x] update base image to use RHEL 9
- [x] Switch python39 to just python3 as 3.9 is the base version in RHEL 9
- [x] updating puppet
- [x] updating anms-core dockerfile
- [x] update authnz dockerfile
```

**Comment by BrianSipos** [comment]
This OS update caused some of the GitLab CI jobs to break, but instead of fixing these the jobs should just be moved to GitHub CI instead to make them visible to the public repo.
