### ISSUE TITLE
Move agent management controls into modal

### ISSUE THREAD

**Issue by njbrunner** [NASA-AMMOS/anms#55]
Move all the controls to manage an agent into the agent modal (#54).

### Acceptance Criteria:
- [ ] Agent controls should be in agent modal
- [ ] Agent controls should be removed from agent list page
- [ ] Agent should be fully controllable via the agent modal
- [ ] Be able to send commands to multiple agents at once
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```
